# Retail Sales & Inventory Exploratory Data Analysis

## 1. Introduction

This notebook contains the exploratory data analysis process for a fictional toy retail chain in Mexico, in particular its retail sales and inventory dataset. The purpose of this analysis is to understand sales behavior, product performance, store-level trends, and inventory-related opportunities.

The final goal is to generate business insights that can support decision-making in a retail environment.

### Main Business Question
**How can sales and inventory data be used to identify business opportunities, improve product performance, and support better store-level decisions?**

### Core Business Questions

1. What are the overall sales trends over time?
2. Which stores generate the highest and lowest revenue?
3. Which products and categories drive most of the sales?
4. Which products have high sales but low inventory?
5. Which products have high inventory but low sales?
6. Which stores show signs of overstocking or understocking?
7. Are there mismatches between inventory availability and sales performance?
8. What business actions can be recommended based on the findings?

## 2. Data Sources & Data Model

The dataset contains the following tables:

- `sales`: transactional fact table with sales by date, store, and product.
- `inventory`: inventory snapshot fact table with current stock by store and product.
- `products`: product dimension table.
- `stores`: store dimension table.
- `calendar`: date dimension table.

## 3. Project Setup

In [2]:
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

sns.set_theme(style="whitegrid")

In [4]:
PROJECT_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

DATA_DIR = PROJECT_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
INTERIM_DATA_DIR = DATA_DIR / "interim"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

REPORTS_DIR = PROJECT_DIR / "reports"
FIGURES_DIR = REPORTS_DIR / "figures"

print("Project directory:", PROJECT_DIR)
print("Raw data directory:", RAW_DATA_DIR)
print("Figures directory:", FIGURES_DIR)

Project directory: /Users/farid/Documents/DataAnalyticsPortfolio/retail_sales_inventory_analysis
Raw data directory: /Users/farid/Documents/DataAnalyticsPortfolio/retail_sales_inventory_analysis/data/raw
Figures directory: /Users/farid/Documents/DataAnalyticsPortfolio/retail_sales_inventory_analysis/reports/figures

## 4. Data Loading

In [15]:
fct_sales = pd.read_csv(RAW_DATA_DIR / "Maven Toys Data/sales.csv")
fct_inventory = pd.read_csv(RAW_DATA_DIR / "Maven Toys Data/inventory.csv")
dim_data_catalog = pd.read_csv(RAW_DATA_DIR / "Maven Toys Data/data_dictionary.csv")
dim_products = pd.read_csv(RAW_DATA_DIR / "Maven Toys Data/products.csv")
dim_stores = pd.read_csv(RAW_DATA_DIR / "Maven Toys Data/stores.csv")
dim_calendar = pd.read_csv(RAW_DATA_DIR / "Maven Toys Data/calendar.csv")

In [19]:
tables = {
    "fct_sales": fct_sales,
    "fct_inventory": fct_inventory,
    "dim_data_catalog": dim_data_catalog,
    "dim_products": dim_products,
    "dim_stores": dim_stores,
    "dim_calendar": dim_calendar
}


for name, table in tables.items():
    print(f"Table: {name}")
    print(f"Shape: {table.shape}")
    print(f"Columns: {table.columns.tolist()}\n")

Table: fct_sales
Shape: (829262, 5)
Columns: ['Sale_ID', 'Date', 'Store_ID', 'Product_ID', 'Units']

Table: fct_inventory
Shape: (1593, 3)
Columns: ['Store_ID', 'Product_ID', 'Stock_On_Hand']

Table: dim_data_catalog
Shape: (19, 3)
Columns: ['Table', 'Field', 'Description']

Table: dim_products
Shape: (35, 5)
Columns: ['Product_ID', 'Product_Name', 'Product_Category', 'Product_Cost', 'Product_Price']

Table: dim_stores
Shape: (50, 5)
Columns: ['Store_ID', 'Store_Name', 'Store_City', 'Store_Location', 'Store_Open_Date']

Table: dim_calendar
Shape: (638, 1)
Columns: ['Date']

# 5. Initial Data Inspection

In [21]:
for name, table in tables.items():
    print(f"\nTable: {name}")
    display(table.head())
    display(table.dtypes)

Table: fct_sales

   Sale_ID        Date  Store_ID  Product_ID  Units
0        1  2022-01-01        24           4      1
1        2  2022-01-01        28           1      1
2        3  2022-01-01         6           8      1
3        4  2022-01-01        48           7      1
4        5  2022-01-01        44          18      1

Sale_ID       int64
Date            str
Store_ID      int64
Product_ID    int64
Units         int64
dtype: object

Table: fct_inventory

   Store_ID  Product_ID  Stock_On_Hand
0         1           1             27
1         1           2              0
2         1           3             32
3         1           4              6
4         1           5              0

Store_ID         int64
Product_ID       int64
Stock_On_Hand    int64
dtype: object

Table: dim_data_catalog

      Table             Field                  Description
0  Products        Product_ID                   Product ID
1  Products      Product_Name                 Product name
2  Products  Product_Category             Product Category
3  Products      Product_Cost          Product cost ($USD)
4  Products     Product_Price  Product retail price ($USD)

Table          str
Field          str
Description    str
dtype: object

Table: dim_products

   Product_ID      Product_Name Product_Category Product_Cost Product_Price
0           1     Action Figure             Toys       $9.99        $15.99
1           2    Animal Figures             Toys       $9.99        $12.99
2           3   Barrel O' Slime     Art & Crafts       $1.99         $3.99
3           4  Chutes & Ladders            Games       $9.99        $12.99
4           5  Classic Dominoes            Games       $7.99         $9.99

Product_ID          int64
Product_Name          str
Product_Category      str
Product_Cost          str
Product_Price         str
dtype: object

Table: dim_stores

,Store_ID,Store_Name,Store_City,Store_Location,Store_Open_Date
0,1,Maven Toys Guadalajara 1,Guadalajara,Residential,1992-09-18
1,2,Maven Toys Monterrey 1,Monterrey,Residential,1995-04-27
2,3,Maven Toys Guadalajara 2,Guadalajara,Commercial,1999-12-27
3,4,Maven Toys Saltillo 1,Saltillo,Downtown,2000-01-01
4,5,Maven Toys La Paz 1,La Paz,Downtown,2001-05-31

Store_ID           int64
Store_Name           str
Store_City           str
Store_Location       str
Store_Open_Date      str
dtype: object

Table: dim_calendar

       Date
0  1/1/2022
1  1/2/2022
2  1/3/2022
3  1/4/2022
4  1/5/2022

Date    str
dtype: object

## 6. Data Quality Assessment

### 6.1 Missing Values

In [29]:
missing_summary = []

for name, table in tables.items():
    missing = table.isna().sum()
    missing_summary.append(
    pd.DataFrame({
        "table": name,
        "column": missing.index,
        "missing_count": missing.sum(),
        "missing_pct": missing.values / len(table) * 100,
        "missing_values": missing.values
    })
    )

missing_summary = pd.concat(missing_summary, ignore_index=True)
missing_summary[missing_summary["missing_values"] > 0]

Empty DataFrame
Columns: [table, column, missing_count, missing_pct, missing_values]
Index: []

### 6.2 Duplicate Records

In [37]:
duplicates_summary = []
for name, table in tables.items():
    duplicates_count = table.duplicated().sum()
    duplicates_summary.append(
        pd.DataFrame({
            "table": name,
            "duplicates_count": [duplicates_count],
            "duplicates_pct": [duplicates_count / len(table) * 100]
        })
    )

duplicates_summary = pd.concat(duplicates_summary, ignore_index=True)
display(duplicates_summary)

              table  duplicates_count  duplicates_pct
0         fct_sales                 0             0.0
1     fct_inventory                 0             0.0
2  dim_data_catalog                 0             0.0
3      dim_products                 0             0.0
4        dim_stores                 0             0.0
5      dim_calendar                 0             0.0

In [ ]:
### REVISAR ESTO
### LLAVES DUPLICADAS SÍ PUEDEN SUCEDER EN LA REALIDAD.

# key_checks = {
#     "sales": ["Sale_ID"],
#     "products": ["Product_ID"],
#     "stores": ["Store_ID"],
#     "calendar": ["Date"],
#     "inventory": ["Store_ID", "Product_ID"]
# }

# key_summary = []

# for table_name, key_cols in key_checks.items():
#     table = tables[table_name]

#     duplicated_keys_count = table.duplicated(subset=key_cols).sum()
#     duplicated_keys_pct = duplicated_keys_count / len(table) * 100

#     key_summary.append({
#         "table": table_name,
#         "key_columns": ", ".join(key_cols),
#         "duplicated_keys_count": duplicated_keys_count,
#         "duplicated_keys_pct": duplicated_keys_pct
#     })

# key_summary = pd.DataFrame(key_summary)
# key_summary

In [10]:
sales = fct_sales.merge(dim_products, on="Product_ID", how="left")\
                 .merge(dim_stores, on="Store_ID", how="left")

In [11]:
sales['Date'] = pd.to_datetime(sales['Date'], format='%Y-%m-%d')
sales['Store_Open_Date'] = pd.to_datetime(sales['Store_Open_Date'], format='%Y-%m-%d')
sales['Product_Cost'] = sales['Product_Cost'].apply(lambda x: x.strip('$')).astype(float)
sales['Product_Price'] = sales['Product_Price'].apply(lambda x: x.strip('$')).astype(float)

In [12]:
sales

,Sale_ID,Date,Store_ID,Product_ID,Units,Product_Name,Product_Category,Product_Cost,Product_Price,Store_Name,Store_City,Store_Location,Store_Open_Date
0,1,2022-01-01,24,4,1,Chutes & Ladders,Games,9.99,12.99,Maven Toys Aguascalientes 1,Aguascalientes,Downtown,2010-07-31
1,2,2022-01-01,28,1,1,Action Figure,Toys,9.99,15.99,Maven Toys Puebla 2,Puebla,Downtown,2011-04-01
2,3,2022-01-01,6,8,1,Deck Of Cards,Games,3.99,6.99,Maven Toys Mexicali 1,Mexicali,Commercial,2003-12-13
3,4,2022-01-01,48,7,1,Dart Gun,Sports & Outdoors,11.99,15.99,Maven Toys Saltillo 2,Saltillo,Commercial,2016-03-23
4,5,2022-01-01,44,18,1,Lego Bricks,Toys,34.99,39.99,Maven Toys Puebla 3,Puebla,Residential,2014-12-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...
829257,829258,2023-09-30,24,19,1,Magic Sand,Art & Crafts,13.99,15.99,Maven Toys Aguascalientes 1,Aguascalientes,Downtown,2010-07-31
829258,829259,2023-09-30,16,35,1,Uno Card Game,Games,3.99,7.99,Maven Toys San Luis Potosi 1,San Luis Potosi,Downtown,2007-05-19
829259,829260,2023-09-30,22,19,1,Magic Sand,Art & Crafts,13.99,15.99,Maven Toys Guanajuato 2,Guanajuato,Commercial,2010-03-29
829260,829261,2023-09-30,13,2,2,Animal Figures,Toys,9.99,12.99,Maven Toys Mexicali 2,Mexicali,Downtown,2006-08-30
829261,829262,2023-09-30,32,6,1,Colorbuds,Electronics,6.99,14.99,Maven Toys Hermosillo 1,Hermosillo,Residential,2012-08-31